BZ #1769893 - Full Capsule sync doesn't fix the broken repository metadata and results in ERROR: "undefined method `[]' for nil:NilClass"
Fixes #28046 - Publish yum distributor on smart proxy (#8381)

(cherry picked from commit 6c2ff4fc97e4f430900e61aef4e71794cca7b5b7)